<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>SeleniumJava</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>SeleniumJava</name>
    <url>http://maven.apache.org</url>
    <properties>
        <java-compiler.version>21</java-compiler.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Dependencies Versions -->
        <selenium.java.version>4.28.0</selenium.java.version>
        <logback.version>1.5.6</logback.version>
        <webdriver.manager.version>5.9.2</webdriver.manager.version>
        <testng.version>7.10.2</testng.version>
        <jackson.version>2.17.2</jackson.version>
        <httpcomponents.version>5.4.1</httpcomponents.version>
        <log4j.version>2.23.1</log4j.version>
        <log4j-api.version>2.23.1</log4j-api.version>
        <log4j-core.version>2.23.1</log4j-core.version>
        <extentReports.version>5.0.9</extentReports.version>
        <apache.poi.version>5.2.4</apache.poi.version>
        <apache.poi.xml.version>5.2.4</apache.poi.xml.version>
        <!-- plugins versions -->
        <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
        <maven.surefire.plugin.version>3.5.2</maven.surefire.plugin.version>
        <maven.dependency.plugin.version>3.7.1</maven.dependency.plugin.version>
        <maven.jar.plugin.version>3.4.1</maven.jar.plugin.version>
        <maven.resource.plugin.version>3.3.1</maven.resource.plugin.version>

        <!-- Setting System Variables from mvn-surefire-plugin -->
        <!--browser.prop>chrome</browser.prop>
        <grid.enabled.prop>false</grid.enabled.prop>
        <grid.url.format.prop>http://%s:4444</grid.url.format.prop>
        <grid.host.prop>localhost</grid.host.prop>
        <screenshot.type>file</screenshot.type>
        <auto.open.execution.report.true>true</auto.open.execution.report.true>
        <test.url.prop>https://the-internet.herokuapp.com/</test.url.prop-->

        <!-- Directories -->
        <docker.package.directory>${project.build.directory}/docker-resources</docker.package.directory>
        <test.output.directory>${project.build.directory}/test-output</test.output.directory>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.java.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>${httpcomponents.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${apache.poi.xml.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.18.0</version>
        </dependency>
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>${extentReports.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <!-- This finalName tag will be the name of the jars that are created by compiling src/{main,test}/java ->
                selenium-docker.jar
                selenium-docker-test.jar
        -->
        <finalName>selenium-docker</finalName>
        <!-- Compiler plugin is used to compile the java project -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <release>${java-compiler.version}</release>
                </configuration>
            </plugin>
            <!-- Surefire is used to trigger tests using mvn test cmd -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <configuration>
                    <!-- We can set systemVariables from pom.xml as well, as shown below -->
                    <!--systemPropertyVariables>
                        <browser>${browser.prop}</browser>
                        <grid.enabled>${grid.enabled.prop}</grid.enabled>
                        <grid.url.format>${grid.url.format.prop}</grid.url.format>
                        <grid.host>${grid.host.prop}</grid.host>
                        <screenshot.type>${screenshot.type}</screenshot.type>
                        <auto.open.execution.report>${auto.open.execution.report.true}</auto.open.execution.report>
                        <test.url>${test.url.prop}</test.url>
                    </systemPropertyVariables-->
                    <suiteXmlFiles>
                        <suiteXmlFile>${project.build.testOutputDirectory}/testSuites/testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <reportsDirectory>${project.build.directory}/test-output/surefire-reports</reportsDirectory>
                </configuration>
            </plugin>
            <!-- dependency plugin is used to copy all the .m2/dependencies.jar to a specific location -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>
                                copy-dependencies
                            </goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${docker.package.directory}/libs
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        <!-- Jar plugin is used to customize the compiled jar, by default mvn compiled only src/main/*
            We have configured mvn to take up src/test/* -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven.jar.plugin.version}</version>
                <configuration>
                    <outputDirectory>
                        ${docker.package.directory}/libs
                    </outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>package-tests-jar</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>
                                test-jar
                            </goal>
                        </goals>
                        <configuration>
                            <includes>
                                **/*.class
                            </includes>
                            <outputDirectory>
                                ${docker.package.directory}/libs
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
<!-- Resources plugin is used to copy src/{main,test}/resources/{log4j,testData,testSuite,configurations} dirs to a specific location -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resource.plugin.version}</version>
                <executions>
<!-- Exec1: To copy .xlsx file from target dir to target/test-output dir which will be created by TestNG post successfull run -->
                    <execution>
                        <id>copy-resources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/test-output</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <includes>
                                        <include>loginTestData.xlsx</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
<!-- Exec2: To copy src/test/resources/* to target/docker-resources -->
                    <execution>
                        <id>copy-test-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>testResources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${docker.package.directory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>