version : "3"
services:
  hub:
    image: selenium/hub:latest
    container_name: hub
  chromeNode:
    image: selenium/node-chrome:latest
    container_name: chromeNode
    shm_size: 2g
    depends_on:
    - hub
    env_file:
    - node.properties # The file extension doesn't matter
    deploy:
      replicas: 0
  firefoxNode:
    image: selenium/node-firefox:latest
    container_name: firefoxNode
    shm_size: 2g
    depends_on:
    - hub
    env_file:
    - node.properties # The file extension doesn't matter
    deploy:
      replicas: 0
    

