# Goals:
#   1. Start the sdasa/selenium-docker test runner container
#   2. Pass the mentioned env variables from Jenkinsfile, if not default values are set from runner.sh
version: "3.8"
services:
  testRunner:
    image: sdasa/selenium-docker:latest
    container_name: testRunner
    environment:
    - GRID_ENABLED=true
    - GRID_HOST # shorthand for GRID_HOST=${GRID_HOST}
    - BROWSER # When using shorthand, you cant define defaults, (i.e) - Browser:-defaultValue
    - THREAD_COUNT # if you want defaults, no shorthands --> - PROP1 = ${PROP1:-defaultValue}